# Generated by Django 2.1 on 2020-10-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_pwd',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
