# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlinux',
            name='linux_passwd',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newlinux',
            name='linux_auth_type',
            field=models.CharField(
                choices=[('password', '密码'), ('key', 'SSH Key')],
                default='password',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='newlinux',
            name='linux_private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newlinux',
            name='linux_private_key_passphrase',
            field=models.TextField(blank=True),
        ),
    ]
