# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('RemoteLinux', '0006_newlinux_ssh_key_auth'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='password',
			field=models.CharField(max_length=128),
		),
		migrations.AlterField(
			model_name='user',
			name='confirm_pwd',
			field=models.CharField(default=None, max_length=128),
		),
	]
