# Generated by Codex on 2026-08-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=64, unique=True)),
                ('credential_hash', models.CharField(max_length=128)),
                ('is_revoked', models.BooleanField(default=False)),
                ('agent_version', models.CharField(blank=True, max_length=64)),
                ('collection_delay_seconds', models.PositiveIntegerField(default=0)),
                ('system_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='RemoteLinux.newlinux')),
            ],
            options={'db_table': 'host_agent'},
        ),
    ]
