from django.urls import path

from . import api, views


app_name = 'devops'

urlpatterns = [
    path('api/bootstrap/', api.bootstrap, name='api_bootstrap'),
    path('api/hosts/', api.hosts, name='api_hosts'),
    path('api/dashboard/', api.dashboard, name='api_dashboard'),
    path('api/commands/', api.commands, name='api_commands'),
    path('api/commands/<int:id>/', api.command_detail, name='api_command_detail'),
    path('api/tasks/', api.tasks, name='api_tasks'),
    path('api/metrics/', api.metrics, name='api_metrics'),
    path('api/alerts/', api.alerts, name='api_alerts'),
    path('api/approvals/', api.approvals, name='api_approvals'),
    path('api/approvals/<int:id>/decide/', api.approval_decide, name='api_approval_decide'),
    path('api/deployments/', api.deployments, name='api_deployments'),
    path('api/files/', api.files, name='api_files'),
    path('api/notifications/', api.notifications, name='api_notifications'),
    path('api/audit-logs/', api.audit_logs, name='api_audit_logs'),
    path('vue/', views.vue_app, name='vue_app'),
    path('legacy/', views.legacy_dashboard, name='legacy_dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.group_create, name='group_create'),
    path('groups/<int:id>/update/', views.group_update, name='group_update'),
    path('groups/<int:id>/delete/', views.group_delete, name='group_delete'),
    path('tags/create/', views.tag_create, name='tag_create'),
    path('tags/<int:id>/update/', views.tag_update, name='tag_update'),
    path('tags/<int:id>/delete/', views.tag_delete, name='tag_delete'),
    path('commands/', views.command_center, name='command_center'),
    path('commands/approvals/create/', views.command_approval_create, name='command_approval_create'),
    path('commands/<int:id>/', views.command_detail, name='command_detail'),
    path('tasks/', views.batch_tasks, name='batch_tasks'),
    path('tasks/<int:id>/', views.batch_task_detail, name='batch_task_detail'),
    path('services/', views.service_manage, name='service_manage'),
    path('metrics/', views.metrics_history, name='metrics_history'),
    path('files/', views.file_distributions, name='file_distributions'),
    path('files/<int:id>/', views.file_distribution_detail, name='file_distribution_detail'),
    path('deployments/', views.deployments, name='deployments'),
    path('deployments/<int:id>/', views.deployment_detail, name='deployment_detail'),
    path('deployments/<int:id>/rollback/', views.deployment_rollback, name='deployment_rollback'),
    path('approvals/', views.approvals, name='approvals'),
    path('approvals/<int:id>/decide/', views.approval_decide, name='approval_decide'),
    path('alerts/', views.alert_events, name='alert_events'),
    path('alerts/<int:id>/update/', views.alert_update, name='alert_update'),
    path('alerts/silences/create/', views.silence_create, name='silence_create'),
    path('alerts/silences/<int:id>/delete/', views.silence_delete, name='silence_delete'),
    path('security/', views.security_settings, name='security_settings'),
    path('security/settings/update/', views.setting_update, name='setting_update'),
    path('security/policies/create/', views.policy_create, name='policy_create'),
    path('security/policies/<int:id>/update/', views.policy_update, name='policy_update'),
    path('security/roles/set/', views.role_set, name='role_set'),
    path('security/modules/set/', views.module_permission_set, name='module_permission_set'),
    path('security/host-scopes/set/', views.host_scope_set, name='host_scope_set'),
    path('notifications/', views.notification_channels, name='notification_channels'),
    path('notifications/create/', views.notification_create, name='notification_create'),
    path('notifications/<int:id>/update/', views.notification_update, name='notification_update'),
    path('notifications/<int:id>/delete/', views.notification_delete, name='notification_delete'),
    path('notifications/<int:id>/test/', views.notification_test, name='notification_test'),
    path('clusters/', views.clusters, name='clusters'),
    path('clusters/connect/', views.cluster_connect, name='cluster_connect'),
    path('clusters/connect/test/', views.cluster_connect_test, name='cluster_connect_test'),
    path('clusters/list/', views.cluster_list, name='cluster_list'),
    path('clusters/create/', views.cluster_create, name='cluster_create'),
    path('clusters/<int:id>/update/', views.cluster_update, name='cluster_update'),
    path('clusters/<int:id>/delete/', views.cluster_delete, name='cluster_delete'),
    path('clusters/<int:id>/test/', views.cluster_test, name='cluster_test'),
    path('clusters/<int:id>/nodes/<str:node_name>/', views.k8s_node_detail, name='k8s_node_detail'),
    path('clusters/<int:id>/', views.k8s_cluster_detail, name='cluster_detail'),
    path('k8s/clusters/', views.cluster_list, name='k8s_cluster_list'),
    path('k8s/clusters/<int:id>/', views.k8s_cluster_detail, name='k8s_cluster_detail'),
    path('audit/', views.audit_logs, name='audit_logs'),
]
