# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('password', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='password',
			name='password',
			field=models.CharField(max_length=512),
		),
	]
