# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='warning', max_length=20)),
                ('metric', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('handler', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_alert_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.TextField()),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '全部成功'), ('partial', '部分成功'), ('failed', '全部失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('hosts', models.ManyToManyField(blank=True, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_batch_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_command_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.ManyToManyField(blank=True, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_host_group',
            },
        ),
        migrations.CreateModel(
            name='ServiceOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('status', '查看状态'), ('start', '启动'), ('stop', '停止'), ('restart', '重启')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_service_operation',
                'ordering': ['-created_at'],
            },
        ),
    ]
