# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='secondary', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.ManyToManyField(blank=True, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_host_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatchTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.CommandExecution')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='devops.BatchTask')),
            ],
            options={
                'db_table': 'devops_batch_task_result',
                'ordering': ['id'],
            },
        ),
    ]
