# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_default_policies(apps, schema_editor):
    CommandPolicy = apps.get_model('devops', 'CommandPolicy')
    defaults = (
        ('删除根目录', 'rm -rf /', 'block', '禁止删除根目录'),
        ('格式化磁盘', 'mkfs', 'block', '禁止格式化磁盘'),
        ('裸写磁盘', 'dd if=', 'block', '禁止直接写磁盘'),
        ('Fork bomb', ':(){', 'block', '禁止 fork bomb'),
        ('关机', 'shutdown', 'require_admin', '关机仅管理员可执行'),
        ('重启', 'reboot', 'require_admin', '重启仅管理员可执行'),
        ('停止系统', 'halt', 'require_admin', '停止系统仅管理员可执行'),
        ('断电', 'poweroff', 'require_admin', '断电仅管理员可执行'),
    )
    for name, pattern, action, reason in defaults:
        CommandPolicy.objects.get_or_create(
            pattern=pattern,
            defaults={
                'name': name,
                'action': action,
                'reason': reason,
                'enabled': True,
            },
        )


def backfill_alert_fingerprint(apps, schema_editor):
    AlertEvent = apps.get_model('devops', 'AlertEvent')
    for alert in AlertEvent.objects.all():
        host_id = alert.host_id or 'none'
        metric = alert.metric or 'general'
        fingerprint = '%s:%s' % (host_id, metric)
        created_at = alert.created_at or django.utils.timezone.now()
        alert.fingerprint = fingerprint
        alert.first_seen_at = created_at
        alert.last_seen_at = alert.updated_at or created_at
        alert.save(update_fields=['fingerprint', 'first_seen_at', 'last_seen_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
        ('devops', '0002_hosttag_batchtaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=200, unique=True)),
                ('action', models.CharField(choices=[('block', '拦截'), ('require_admin', '仅管理员可执行'), ('allow', '允许')], default='block', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_command_policy',
                'ordering': ['pattern'],
            },
        ),
        migrations.CreateModel(
            name='DevOpsRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', '只读'), ('operator', '运维操作'), ('admin', '管理员')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.User')),
            ],
            options={
                'db_table': 'devops_role',
            },
        ),
        migrations.AddField(
            model_name='alertevent',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='repeat_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AlertSilence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(blank=True, max_length=50)),
                ('reason', models.CharField(max_length=300)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_alert_silence',
                'ordering': ['-ends_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('handler', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='devops.AlertEvent')),
            ],
            options={
                'db_table': 'devops_alert_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_default_policies, migrations.RunPython.noop),
        migrations.RunPython(backfill_alert_fingerprint, migrations.RunPython.noop),
    ]
