# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
        ('devops', '0003_policy_role_alert_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('cpu', 'CPU'), ('memory', '内存'), ('disk', '磁盘')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='percent', max_length=20)),
                ('collected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_metric_sample',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['host', 'metric', '-collected_at'], name='devops_metr_host_id_350573_idx'),
        ),
    ]
