# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion
import devops.models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
        ('devops', '0004_metric_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_file', models.FileField(upload_to=devops.models.devops_upload_path)),
                ('remote_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', '等待分发'), ('running', '分发中'), ('success', '全部成功'), ('partial', '部分成功'), ('failed', '全部失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('hosts', models.ManyToManyField(blank=True, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_file_distribution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDistributionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='devops.FileDistribution')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_file_distribution_result',
                'ordering': ['id'],
            },
        ),
    ]
