# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
        ('devops', '0005_file_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devops_deployment_app',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('deploy_script', models.TextField()),
                ('rollback_script', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '等待发布'), ('running', '发布中'), ('success', '发布成功'), ('partial', '部分成功'), ('failed', '发布失败'), ('blocked', '已拦截'), ('rolled_back', '已回滚')], default='pending', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.DeploymentApp')),
                ('hosts', models.ManyToManyField(blank=True, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_deployment_release',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deploy', '发布'), ('rollback', '回滚')], default='deploy', max_length=20)),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.CommandExecution')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='devops.DeploymentRelease')),
            ],
            options={
                'db_table': 'devops_deployment_result',
                'ordering': ['id'],
            },
        ),
    ]
