# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0005_user_confirm_pwd'),
        ('devops', '0006_deployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('command', '命令执行'), ('deployment', '发布部署')], max_length=30)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('executed', '已执行'), ('failed', '执行失败')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('requester', models.CharField(blank=True, max_length=100)),
                ('approver', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('command', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('command_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.CommandExecution')),
                ('deployment_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.DeploymentRelease')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_approval_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
