# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0007_approval_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevOpsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_deploy_approval', models.BooleanField(default=False)),
                ('force_rollback_approval', models.BooleanField(default=False)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devops_setting',
            },
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(
                choices=[
                    ('command', '命令执行'),
                    ('deployment', '发布部署'),
                    ('rollback', '发布回滚'),
                ],
                max_length=30,
            ),
        ),
    ]
