# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0008_devops_setting_rollback_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('wecom', '企业微信'), ('dingtalk', '钉钉'), ('webhook', 'Webhook')], default='webhook', max_length=20)),
                ('webhook_url', models.TextField()),
                ('secret', models.TextField(blank=True)),
                ('notify_alert', models.BooleanField(default=True)),
                ('notify_approval', models.BooleanField(default=True)),
                ('notify_deployment', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devops_notification_channel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('alert', '告警'), ('approval', '审批'), ('deployment', '发布'), ('test', '测试')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='devops.NotificationChannel')),
            ],
            options={
                'db_table': 'devops_notification_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
