# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0006_newlinux_ssh_key_auth'),
        ('devops', '0009_notification_channel_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevOpsHostScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.User')),
            ],
            options={
                'db_table': 'devops_host_scope',
                'ordering': ['user__user'],
            },
        ),
        migrations.CreateModel(
            name='DevOpsModulePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('command', '命令执行'), ('task', '批量任务'), ('service', '服务管理'), ('file', '文件分发'), ('deployment', '发布部署'), ('approval', '审批流'), ('alert', '告警治理'), ('metric', '监控历史'), ('security', '安全策略'), ('audit', '审计日志')], max_length=30)),
                ('role', models.CharField(choices=[('viewer', '只读'), ('operator', '运维操作'), ('admin', '管理员')], default='viewer', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.User')),
            ],
            options={
                'db_table': 'devops_module_permission',
                'ordering': ['user__user', 'module'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.AddField(
            model_name='devopshostscope',
            name='groups',
            field=models.ManyToManyField(blank=True, to='devops.HostGroup'),
        ),
    ]
