# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0010_finer_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='devopshostscope',
            name='tags',
            field=models.ManyToManyField(blank=True, to='devops.HostTag'),
        ),
    ]
