# Generated by Django 2.1.7 on 2026-07-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0013_initial_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceBaseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('baseline_type', models.CharField(choices=[('service_active', '服务运行状态'), ('file_sha256', '文件 SHA-256')], max_length=30)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('expected_sha256', models.CharField(blank=True, max_length=64)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosts', models.ManyToManyField(blank=True, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_compliance_baseline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('compliant', '符合'), ('drift', '存在漂移'), ('error', '扫描失败')], max_length=20)),
                ('actual_value', models.CharField(blank=True, max_length=100)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='devops.ComplianceBaseline')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_compliance_result',
                'ordering': ['baseline__name', 'host__linux_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='complianceresult',
            unique_together={('baseline', 'host')},
        ),
    ]
