# Generated by Codex on 2026-07-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0014_compliance_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(choices=[('development', '开发'), ('test', '测试'), ('staging', '预发布'), ('production', '生产')], default='production', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosts', models.ManyToManyField(blank=True, related_name='topology_services', to='RemoteLinux.NewLinux')),
            ],
            options={
                'db_table': 'devops_service_catalog',
                'ordering': ['environment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_links', to='devops.ServiceCatalog')),
                ('upstream_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_links', to='devops.ServiceCatalog')),
            ],
            options={
                'db_table': 'devops_service_dependency',
                'ordering': ['service__name', 'upstream_service__name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='servicedependency',
            unique_together={('service', 'upstream_service')},
        ),
    ]
