# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0015_service_catalog_topology'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='failure_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('alert', '告警'), ('approval', '审批'), ('deployment', '发布')], max_length=30, unique=True)),
                ('title_template', models.CharField(blank=True, max_length=150)),
                ('content_template', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'devops_notification_template', 'ordering': ['event_type']},
        ),
        migrations.CreateModel(
            name='AlertNotificationEscalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('minimum_level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], default='critical', max_length=20)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_rules', to='devops.NotificationChannel')),
            ],
            options={'db_table': 'devops_alert_notification_escalation'},
        ),
    ]
