# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0001_initial'),
        ('devops', '0016_notification_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', '已打开'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20)),
                ('root_cause', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.AlertEvent')),
                ('command_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.CommandExecution')),
                ('deployment_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.DeploymentRelease')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RemoteLinux.NewLinux')),
            ],
            options={'db_table': 'devops_incident', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='devops.Incident')),
            ],
            options={'db_table': 'devops_incident_timeline', 'ordering': ['created_at', 'id']},
        ),
    ]
