# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0017_incident_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentapp',
            name='repository',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DevOpsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('monitor_cpu', models.CharField(default='80%', max_length=20)),
                ('monitor_memory', models.CharField(default='80%', max_length=20)),
                ('monitor_disk', models.CharField(default='80%', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_apps', models.ManyToManyField(blank=True, related_name='devops_projects', to='devops.DeploymentApp')),
                ('groups', models.ManyToManyField(blank=True, related_name='devops_projects', to='devops.HostGroup')),
                ('hosts', models.ManyToManyField(blank=True, related_name='devops_projects', to='RemoteLinux.NewLinux')),
                ('services', models.ManyToManyField(blank=True, related_name='devops_projects', to='devops.ServiceCatalog')),
                ('tags', models.ManyToManyField(blank=True, related_name='devops_projects', to='devops.HostTag')),
            ],
            options={
                'db_table': 'devops_project',
                'ordering': ['name'],
            },
        ),
    ]
