# Generated by Codex on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0018_project_onboarding_and_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('command', '命令执行'), ('batch_task', '批量任务'), ('file_distribution', '文件分发'), ('deployment', '发布部署'), ('rollback', '发布回滚')], max_length=30)),
                ('target_id', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devops_background_job',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['status', 'id'], name='devops_back_status_4bee48_idx'),
        ),
    ]
