# Generated by Codex on 2026-07-19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0019_background_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationHealthEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('prometheus', 'Prometheus'), ('alertmanager', 'Alertmanager'), ('github_inbound', 'GitHub 入站'), ('notification', '通知渠道')], max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20)),
                ('category', models.CharField(choices=[('ok', '正常'), ('http_error', 'HTTP 错误'), ('timeout', '超时'), ('request_error', '请求异常'), ('configuration', '配置异常'), ('validation_error', '校验失败'), ('rejected', '已拒绝'), ('duplicate', '重复投递'), ('unavailable', '服务不可用'), ('internal_error', '内部异常')], max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'devops_integration_health_event',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationhealthevent',
            index=models.Index(fields=['integration_type', 'source_id', '-occurred_at'], name='devops_ihe_type_ref_5b36b3_idx'),
        ),
    ]
