# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0020_integration_health_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosts', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='RemoteLinux.NewLinux')),
                ('services', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='devops.ServiceCatalog')),
            ],
            options={
                'db_table': 'devops_maintenance_window',
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancewindow',
            index=models.Index(fields=['enabled', 'starts_at', 'ends_at'], name='devops_mw_active_7ed7d1_idx'),
        ),
    ]
