# Generated by Django 4.2.16 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0021_maintenance_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsmodulepermission',
            name='role',
            field=models.CharField(
                choices=[
                    ('viewer', '只读'),
                    ('operator', '运维操作'),
                    ('admin', '管理员'),
                    ('none', '禁止访问'),
                ],
                default='viewer',
                max_length=20,
            ),
        ),
    ]
