# Generated by Django 4.2.16 on 2026-07-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0022_module_permission_deny_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_kind', models.CharField(choices=[('availability', '可用性'), ('latency', '延迟'), ('error_rate', '错误率')], max_length=20)),
                ('target', models.DecimalField(decimal_places=3, max_digits=8)),
                ('window_minutes', models.PositiveIntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('last_state', models.CharField(choices=[('healthy', '健康'), ('exhausted', '预算耗尽'), ('unavailable', '指标不可用')], default='unavailable', max_length=20)),
                ('last_summary', models.CharField(blank=True, max_length=200)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slos', to='devops.servicecatalog')),
            ],
            options={
                'db_table': 'devops_service_slo',
                'ordering': ['service__name', 'metric_kind', 'id'],
                'unique_together': {('service', 'metric_kind')},
            },
        ),
    ]
