# Generated by Django 4.2.16 on 2026-07-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0023_service_slo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunbookTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('trigger_kind', models.CharField(choices=[('alert', '告警'), ('service', '服务处置'), ('manual', '人工发起')], default='manual', max_length=20)),
                ('command_template', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_hosts', models.ManyToManyField(blank=True, related_name='runbook_templates', to='RemoteLinux.newlinux')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbook_templates', to='devops.servicecatalog')),
            ],
            options={
                'db_table': 'devops_runbook_template',
                'ordering': ['name', '-version', 'id'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
