# Generated by Django 4.2.16 on 2026-07-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0024_runbook_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='runbook_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_executions', to='devops.runbooktemplate'),
        ),
    ]
