# Generated by Django 4.2.16 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0026_service_slo_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslo',
            name='last_notification_state',
            field=models.CharField(
                choices=[
                    ('healthy', '健康'),
                    ('exhausted', '预算耗尽'),
                    ('unavailable', '指标不可用'),
                ],
                default='unavailable',
                max_length=20,
            ),
        ),
    ]
