# Generated by Django 4.2.16 on 2026-07-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0027_serviceslo_last_notification_state'),
        ('RemoteLinux', '0008_initial_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusRuleRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=253)),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=20)),
                ('desired_yaml', models.TextField(blank=True)),
                ('desired_digest', models.CharField(blank=True, max_length=64)),
                ('baseline_resource_version', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待复核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('published', '已发布'), ('failed', '发布失败')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('publish_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prometheus_rule_revisions', to='devops.k8scluster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prometheus_rule_revisions', to='RemoteLinux.user')),
            ],
            options={
                'db_table': 'devops_prometheus_rule_revision',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='prometheusrulerevision',
            index=models.Index(fields=['cluster', 'namespace', 'name'], name='devops_prom_cluster_e88a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='prometheusrulerevision',
            index=models.Index(fields=['status'], name='devops_prom_status_9e50db_idx'),
        ),
        migrations.CreateModel(
            name='PrometheusRuleRevisionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', '批准'), ('reject', '拒绝')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prometheus_rule_reviews', to='RemoteLinux.user')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='devops.prometheusrulerevision')),
            ],
            options={
                'db_table': 'devops_prometheus_rule_revision_review',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
