# Generated by Django 4.2.16 on 2026-07-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0028_prometheus_rule_revision_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOnCallPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_oncall_policies', to='devops.notificationchannel')),
                ('backup_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_oncall_policies', to='RemoteLinux.user')),
                ('primary_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_oncall_policies', to='devops.notificationchannel')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_oncall_policies', to='RemoteLinux.user')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_policy', to='devops.servicecatalog')),
            ],
            options={
                'db_table': 'devops_service_oncall_policy',
                'ordering': ['service__name'],
            },
        ),
        migrations.CreateModel(
            name='AlertOnCallEscalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '等待确认'), ('acknowledged', '已确认'), ('escalated', '已升级'), ('cancelled', '已取消'), ('failed', '发送失败')], default='active', max_length=20)),
                ('primary_notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('backup_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('backup_notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_category', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_escalations', to='devops.alertevent')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_escalations', to='devops.serviceoncallpolicy')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_oncall_escalations', to='devops.servicecatalog')),
            ],
            options={
                'db_table': 'devops_alert_oncall_escalation',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'primary_notified_at'], name='devops_oncall_due_idx')],
                'unique_together': {('alert', 'service')},
            },
        ),
    ]
