# Generated by Django 4.2.16 on 2026-07-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0029_serviceoncallpolicy_alertoncallescalation'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sWorkloadServiceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=63)),
                ('workload_kind', models.CharField(choices=[('Deployment', 'Deployment'), ('StatefulSet', 'StatefulSet'), ('DaemonSet', 'DaemonSet')], max_length=20)),
                ('workload_name', models.CharField(max_length=253)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_workload_mappings', to='devops.k8scluster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k8s_workload_mappings', to='devops.servicecatalog')),
            ],
            options={
                'db_table': 'devops_k8s_workload_service_mapping',
                'ordering': ['cluster__name', 'namespace', 'workload_kind', 'workload_name'],
                'unique_together': {('cluster', 'namespace', 'workload_kind', 'workload_name')},
            },
        ),
    ]
