# Generated by Django 4.2.16 on 2026-07-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0030_k8sworkloadservicemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOnCallRotationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oncall_rotation_members', to='devops.notificationchannel')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_members', to='devops.serviceoncallpolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oncall_rotation_members', to='RemoteLinux.user')),
            ],
            options={
                'db_table': 'devops_service_oncall_rotation_member',
                'ordering': ['policy_id', 'position', 'id'],
                'unique_together': {('policy', 'position')},
            },
        ),
    ]
