# Generated by Django 4.2.16 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0031_serviceoncallrotationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], default='pending', max_length=20)),
                ('last_summary', models.CharField(blank=True, max_length=200)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devops_scheduled_task_run',
                'ordering': ['task_name'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledtaskrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='devops_sched_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtaskrun',
            index=models.Index(fields=['next_run_at'], name='devops_sched_next_idx'),
        ),
    ]
