# Generated by Django 4.2.16 on 2026-07-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0032_scheduledtaskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=128)),
                ('advisory_id', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], max_length=20)),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已处理')], default='open', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_findings', to='RemoteLinux.newlinux')),
            ],
            options={
                'db_table': 'devops_vulnerability_finding',
                'indexes': [models.Index(fields=['status', 'severity'], name='devops_vuln_status_a4e98e_idx')],
                'unique_together': {('host', 'package_name', 'advisory_id')},
            },
        ),
        migrations.CreateModel(
            name='GitOpsDriftFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=63)),
                ('resource_name', models.CharField(max_length=253)),
                ('resource_kind', models.CharField(max_length=40)),
                ('desired_digest', models.CharField(max_length=64)),
                ('observed_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('drifted', '存在漂移'), ('in_sync', '已同步')], default='drifted', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gitops_drift_findings', to='devops.k8scluster')),
            ],
            options={
                'db_table': 'devops_gitops_drift_finding',
                'indexes': [models.Index(fields=['cluster', 'status'], name='devops_gito_cluster_b1e102_idx')],
                'unique_together': {('cluster', 'namespace', 'resource_name', 'resource_kind')},
            },
        ),
    ]
