# Generated by Codex on 2026-07-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0033_governance_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident', name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident', name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident', name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InspectionRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('recommended', '已建议'), ('initiated', '已提交审批')], default='recommended', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='devops.complianceresult')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_recommendations', to='RemoteLinux.newlinux')),
                ('initiated_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.approvalrequest')),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_recommendations', to='devops.runbooktemplate')),
            ],
            options={'db_table': 'devops_inspection_recommendation', 'ordering': ['-created_at'], 'unique_together': {('compliance_result', 'runbook')}},
        ),
    ]
