# Generated by Django 4.2.16 on 2026-07-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0034_incident_command_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='criticality',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '关键')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='lifecycle',
            field=models.CharField(choices=[('active', '运行中'), ('maintenance', '维护中'), ('retired', '已退役')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CloudResourceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('aliyun', '阿里云')], max_length=20)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_identifier', models.CharField(max_length=160)),
                ('region', models.CharField(max_length=64)),
                ('tag_digest', models.CharField(max_length=64)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_resources', to='devops.servicecatalog')),
            ],
            options={
                'db_table': 'devops_cloud_resource_summary',
                'ordering': ['provider', 'region', 'resource_type', 'resource_identifier'],
                'unique_together': {('provider', 'resource_type', 'resource_identifier', 'region')},
            },
        ),
        migrations.CreateModel(
            name='CloudDailyCostSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='devops.cloudresourcesummary')),
            ],
            options={
                'db_table': 'devops_cloud_daily_cost_summary',
                'ordering': ['-cost_date', 'resource__provider', 'resource__resource_identifier'],
                'unique_together': {('resource', 'cost_date', 'currency')},
            },
        ),
    ]
