# Generated by Django 4.2.16 on 2026-07-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0036_merge_20260727_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('jenkins', 'Jenkins'), ('gitlab', 'GitLab')], max_length=20)),
                ('repository', models.CharField(max_length=200)),
                ('delivery_id', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('revision', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci_deliveries', to='devops.deploymentrelease')),
            ],
            options={
                'db_table': 'devops_ci_delivery',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cidelivery',
            index=models.Index(fields=['repository', 'revision'], name='devops_ci_repo_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='cidelivery',
            index=models.Index(fields=['status', '-received_at'], name='devops_ci_status_time_idx'),
        ),
    ]
