# Generated by Django 4.2.16 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0037_ci_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentrelease',
            name='rollout_batch_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeploymentHealthEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_identity', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('healthy', '健康'), ('unhealthy', '不健康')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=100)),
                ('summary', models.CharField(max_length=300)),
                ('evaluated_at', models.DateTimeField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_evaluations', to='devops.deploymentrelease')),
            ],
            options={
                'db_table': 'devops_deployment_health_evaluation',
                'ordering': ['-evaluated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='deploymenthealthevaluation',
            index=models.Index(fields=['release', '-evaluated_at'], name='devops_release_health_idx'),
        ),
    ]
