# Generated by Django 4.2.16 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('devops', '0038_deployment_health_guard')]

    operations = [
        migrations.CreateModel(
            name='AlertQualityFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('valid', '有效告警'), ('noise', '噪声告警'), ('duplicate', '重复告警'), ('threshold', '阈值待优化')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_feedbacks', to='devops.alertevent')),
            ],
            options={'db_table': 'devops_alert_quality_feedback', 'ordering': ['-created_at', '-id']},
        ),
        migrations.AddIndex(model_name='alertqualityfeedback', index=models.Index(fields=['alert', '-created_at'], name='devops_alert_quality_idx')),
    ]
