# Generated by Django 4.2.16 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('devops', '0039_alert_quality_feedback')]

    operations = [
        migrations.CreateModel(
            name='RunbookEffectivenessFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('effective', '有效'), ('partial', '部分有效'), ('ineffective', '无效')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_feedbacks', to='devops.commandexecution')),
            ],
            options={
                'db_table': 'devops_runbook_effectiveness_feedback',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='runbookeffectivenessfeedback',
            index=models.Index(fields=['command_execution', '-created_at'], name='devops_runbook_effect_idx'),
        ),
    ]
