# Generated by Django 4.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('devops', '0040_runbook_effectiveness_feedback')]

    operations = [
        migrations.AddField(
            model_name='servicesloevaluation',
            name='observed_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicesloevaluation',
            name='budget_remaining_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='servicesloevaluation',
            name='burn_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
