# Generated by Django 4.2.16 on 2026-08-03 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0041_servicesloevaluation_burn_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=True)),
                ('definition_digest', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devops_infrastructure_blueprint',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('connector_type', models.CharField(choices=[('gitops', 'GitOps'), ('vulnerability', '漏洞导入')], max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=True)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('config_encrypted', models.TextField(blank=True)),
                ('last_status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='blocked', max_length=20)),
                ('last_outcome_category', models.CharField(blank=True, max_length=40)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devops_integration_connector',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityImportRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('outcome_category', models.CharField(blank=True, max_length=40)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulnerability_runs', to='devops.integrationconnector')),
            ],
            options={
                'db_table': 'devops_vulnerability_import_run',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['connector', '-created_at'], name='devops_vir_connector_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='InfrastructurePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('outcome_category', models.CharField(blank=True, max_length=40)),
                ('definition_digest', models.CharField(blank=True, max_length=64)),
                ('resource_count', models.PositiveIntegerField(default=0)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('requested_by', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='devops.infrastructureblueprint')),
            ],
            options={
                'db_table': 'devops_infrastructure_plan',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['blueprint', '-created_at'], name='devops_ip_blueprint_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='GitOpsCollectionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '已拦截')], default='pending', max_length=20)),
                ('outcome_category', models.CharField(blank=True, max_length=40)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gitops_runs', to='devops.integrationconnector')),
            ],
            options={
                'db_table': 'devops_gitops_collection_run',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['connector', '-created_at'], name='devops_gcr_connector_time_idx')],
            },
        ),
    ]
