# Generated by Django 4.2.16 on 2026-08-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
        ('devops', '0042_controlled_integrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOpsIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wecom_user_id', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatops_identity', to='RemoteLinux.user')),
            ],
            options={
                'db_table': 'devops_chatops_identity',
                'ordering': ['wecom_user_id'],
            },
        ),
    ]
