# Generated by Django 4.2.16 on 2026-08-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0009_host_agent'),
        ('devops', '0043_chatops_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentActionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_action_items', to='RemoteLinux.user')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='devops.incident')),
            ],
            options={
                'db_table': 'devops_incident_action_item',
                'ordering': ['status', 'due_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['incident', 'status'], name='devops_ia_incident_status_idx'), models.Index(fields=['status', 'due_at'], name='devops_ia_status_due_idx')],
            },
        ),
    ]
