# Generated by Django 4.2.16 on 2026-08-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLinux', '0009_host_agent'),
        ('devops', '0044_incidentactionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertQualityGovernanceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_key', models.CharField(max_length=96, unique=True)),
                ('metric', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('valid', '有效告警'), ('noise', '噪声告警'), ('duplicate', '重复告警'), ('threshold', '阈值待优化')], max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('implemented', '已实施')], default='open', max_length=20)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_quality_governance_reviews', to='RemoteLinux.user')),
                ('rule_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_quality_governance_reviews', to='devops.prometheusrulerevision')),
            ],
            options={
                'db_table': 'devops_alert_quality_governance_review',
                'ordering': ['status', '-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='devops_aqgr_status_seen_idx'), models.Index(fields=['metric', 'classification'], name='devops_aqgr_metric_class_idx')],
            },
        ),
    ]
