# Generated by Django 4.2.16 on 2026-08-07 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0047_alter_notificationlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runbooktemplate',
            name='rollback_runbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_runbooks', to='devops.runbooktemplate'),
        ),
        migrations.CreateModel(
            name='RunbookHealthVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', '健康'), ('unhealthy', '不健康')], max_length=20)),
                ('active_critical_alert_count', models.PositiveIntegerField(default=0)),
                ('summary', models.CharField(max_length=200)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('command_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_verification', to='devops.commandexecution')),
                ('rollback_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbook_health_verifications', to='devops.approvalrequest')),
            ],
            options={
                'db_table': 'devops_runbook_health_verification',
                'ordering': ['-verified_at', '-id'],
                'indexes': [models.Index(fields=['status', '-verified_at'], name='devops_runbook_health_idx')],
            },
        ),
    ]
