# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='AiopsAlertAnalysis',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('alert_name', models.CharField(blank=True, max_length=200)),
				('severity', models.CharField(blank=True, max_length=50)),
				('instance', models.CharField(blank=True, max_length=200)),
				('source', models.CharField(default='alertmanager', max_length=100)),
				('raw_payload', models.TextField()),
				('summary', models.TextField(blank=True)),
				('suggestion', models.TextField(blank=True)),
				('llm_response', models.TextField(blank=True)),
				('status', models.CharField(choices=[('received', '已接收'), ('analyzed', '已分析'), ('failed', '分析失败')], default='received', max_length=20)),
				('error', models.TextField(blank=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
			],
			options={
				'db_table': 'aiops_alert_analysis',
				'ordering': ['-created_at'],
			},
		),
		migrations.CreateModel(
			name='AiopsIntegration',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('alertmanager_url', models.URLField(blank=True)),
				('llm_url', models.URLField(blank=True)),
				('llm_api_key', models.CharField(blank=True, max_length=300)),
				('llm_model', models.CharField(blank=True, default='gpt-4o-mini', max_length=100)),
				('enabled', models.BooleanField(default=True)),
				('updated_by', models.CharField(blank=True, max_length=100)),
				('updated_at', models.DateTimeField(auto_now=True)),
			],
			options={
				'db_table': 'aiops_integration',
			},
		),
	]
