# Generated by Codex on 2026-07-21

from django.db import migrations, models


def secure_existing_aiops_data(apps, schema_editor):
	from PyLinux.crypto import encrypt_text

	Integration = apps.get_model('aiops', 'AiopsIntegration')
	Analysis = apps.get_model('aiops', 'AiopsAlertAnalysis')
	for integration in Integration.objects.exclude(llm_api_key='').iterator():
		integration.llm_api_key = encrypt_text(integration.llm_api_key)
		integration.save(update_fields=['llm_api_key'])
	Analysis.objects.exclude(raw_payload='').update(raw_payload='')
	Analysis.objects.exclude(summary='').update(summary='')
	Analysis.objects.exclude(suggestion='').update(suggestion='')
	Analysis.objects.exclude(llm_response='').update(llm_response='')
	Analysis.objects.exclude(error='').update(error='')


class Migration(migrations.Migration):

	dependencies = [
		('aiops', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='aiopsintegration',
			name='llm_api_key',
			field=models.TextField(blank=True),
		),
		migrations.AlterField(
			model_name='aiopsalertanalysis',
			name='raw_payload',
			field=models.TextField(blank=True, default=''),
		),
		migrations.AlterField(
			model_name='aiopsalertanalysis',
			name='llm_response',
			field=models.TextField(blank=True, default=''),
		),
		migrations.RunPython(secure_existing_aiops_data, migrations.RunPython.noop),
	]
