# Generated by Django 4.2.16 on 2026-08-07 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0047_alter_notificationlog_event_type'),
        ('RemoteLinux', '0009_host_agent'),
        ('aiops', '0003_aiops_safe_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiopsRunbookRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('recommended', '已建议'), ('initiated', '已提交审批')], default='recommended', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiops_runbook_recommendations', to='devops.alertevent')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiops_runbook_recommendations', to='RemoteLinux.newlinux')),
                ('initiated_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.approvalrequest')),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aiops_runbook_recommendations', to='devops.runbooktemplate')),
            ],
            options={
                'db_table': 'aiops_runbook_recommendation',
                'ordering': ['-created_at', '-id'],
                'unique_together': {('alert', 'runbook')},
            },
        ),
    ]
