# Generated by Codex on 2026-08-11

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

	dependencies = [
		('aiops', '0004_aiopsrunbookrecommendation'),
		('devops', '0047_alter_notificationlog_event_type'),
		('RemoteLinux', '0009_host_agent'),
	]

	operations = [
		migrations.CreateModel(
			name='AiopsInvestigation',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_by', models.CharField(blank=True, max_length=100)),
				('status', models.CharField(choices=[('open', '待分析'), ('analyzing', '分析中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], db_index=True, default='open', max_length=20)),
				('title', models.CharField(max_length=200)),
				('window_key', models.CharField(choices=[('1h', '最近 1 小时'), ('6h', '最近 6 小时'), ('24h', '最近 24 小时'), ('7d', '最近 7 天')], default='24h', max_length=20)),
				('window_start', models.DateTimeField()),
				('window_end', models.DateTimeField()),
				('risk', models.CharField(choices=[('unknown', '未知'), ('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], db_index=True, default='unknown', max_length=20)),
				('confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
				('summary', models.CharField(blank=True, max_length=1000)),
				('root_cause_summary', models.CharField(blank=True, max_length=2000)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('hosts', models.ManyToManyField(blank=True, related_name='aiops_investigations', to='RemoteLinux.newlinux')),
				('services', models.ManyToManyField(blank=True, related_name='aiops_investigations', to='devops.servicecatalog')),
			],
			options={
				'db_table': 'aiops_investigation',
				'ordering': ['-created_at', '-id'],
			},
		),
	]
