# Generated by Django 2.1 on 2020-01-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_email', models.EmailField(max_length=254)),
                ('monitor_cpu', models.FloatField()),
                ('monitor_men', models.FloatField()),
                ('monitor_disk', models.FloatField()),
            ],
            options={
                'db_table': 'monitor-info',
            },
        ),
    ]
