# Generated by Django 2.1 on 2020-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200116_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='monitor_cpu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_disk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_men',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
