# Generated by Django 2.1 on 2020-01-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20200118_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='monitor_cpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_disk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_men',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
