# Generated by Django 2.1.7 on 2026-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20200118_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prometheus_url', models.URLField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitor-prometheus-config',
            },
        ),
    ]
