# Generated by Django 2.1.7 on 2026-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_prometheusconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信')], max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('webhook_url', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitor-alert-notification',
            },
        ),
    ]
