# Generated by Django 2.1.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alertnotificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='prometheusconfig',
            name='name',
            field=models.CharField(default='Prometheus', max_length=100),
        ),
        migrations.CreateModel(
            name='AlertmanagerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alertmanager_url', models.URLField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitor-alertmanager-config',
            },
        ),
    ]
