# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_prometheusconfig_name_alertmanagerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationconfig',
            name='alert_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
