# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alertnotificationconfig_alert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationconfig',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertnotificationconfig',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
