# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alertnotificationconfig_created_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationconfig',
            name='provider',
            field=models.CharField(choices=[('feishu', '飞书'), ('wecom', '企业微信')], max_length=20),
        ),
    ]
