# Generated by Codex on 2026-07-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_alertnotificationconfig_provider_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationconfig',
            name='alertmanager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notification_configs',
                to='monitor.AlertmanagerConfig',
            ),
        ),
    ]
