# Generated by Django 4.2.16 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RemoteLinux', '0008_initial_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('oidc', 'OIDC'), ('ldap', 'LDAP')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='external_identity', to='RemoteLinux.user')),
            ],
            options={
                'db_table': 'userprofile_external_identity',
                'unique_together': {('provider', 'subject')},
            },
        ),
    ]
